login:
    path: /login
    methods: GET
    controller: App\Controller\HomeController::home

logout:
    path: /logout

dashboard:
    path: /admindashboard
    methods: GET
    controller: App\Controller\Administrateur\DashboardController::start

adminuser:
    path: /adminuser
    methods: GET
    controller: App\Controller\Administrateur\AdminUserController::home

settingsadmin:
    path: /settingsadmin
    methods: GET
    controller: App\Controller\Administrateur\SettingsController::settings

utilisateurs:
    path: /utilisateurs
    methods: GET
    controller: App\Controller\Administrateur\UtilisateursController::home

listusers:
    path: /listusers
    methods: GET
    controller: App\Controller\Administrateur\UtilisateursController::listUsers

signalements:
    path: /signalements
    methods: GET
    controller: App\Controller\Administrateur\SignalementsController::home

signalement_list:
    path: /signalements/id
    methods: GET
    controller: App\Controller\Administrateur\SignalementsController::getUserSignal  
    
listSignal:
    path: /listSignal/id
    methods: GET
    controller: App\Controller\Administrateur\SignalementsController::listReporting

chaines:
    path: /chaines
    methods: GET
    controller: App\Controller\Administrateur\ChainesController::home

listchannels:
    path: /listchannels
    methods: GET
    controller: App\Controller\Administrateur\ChainesController::allchannels

adduser:
    path: /adduser
    methods: GET
    controller: App\Controller\Administrateur\CrudController::getUser

newuser:
    path: /newuser
    methods: GET
    controller: App\Controller\Administrateur\CrudController::addNewUser

edituser:
    path: /edituser/id
    methods: GET
    controller: App\Controller\Administrateur\CrudController::editUser

userdashboard:
    path: /userdashboard
    methods: GET
    controller: App\Controller\Users\DashboardUserController::start

planning:
    path: /planning
    methods: GET
    controller: App\Controller\PlanningController::start

radios:
    path: /radios
    methods: GET
    controller: App\Controller\Users\RadiosController::start

listradios:
    path: /listradios
    methods: GET
    controller: App\Controller\Users\RadiosController::getAllRadio

settings:
    path: /settings
    methods: GET
    controller: App\Controller\Users\SettingsController::accountSetting

musiclibrary:
    path: /musiclibrary
    methods: GET
    controller: App\Controller\Users\MusicLibraryController::start

timeline:
    path: /timeline
    methods: GET
    controller: App\Controller\Users\TimelineController::start
