<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerEVxNYqF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEVxNYqF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEVxNYqF.legacy');
=======
if (\class_exists(\ContainerTLlxTHW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLlxTHW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTLlxTHW.legacy');
>>>>>>> a480cfbb121d5ad367ba2863c027d871195e994c

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerEVxNYqF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEVxNYqF\App_KernelDevDebugContainer([
    'container.build_hash' => 'EVxNYqF',
    'container.build_id' => '77dff8ae',
    'container.build_time' => 1582816326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEVxNYqF');
=======
    \class_alias(\ContainerTLlxTHW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTLlxTHW\App_KernelDevDebugContainer([
    'container.build_hash' => 'TLlxTHW',
    'container.build_id' => '463f3c2d',
    'container.build_time' => 1582794888,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLlxTHW');
>>>>>>> a480cfbb121d5ad367ba2863c027d871195e994c
