<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUU9NG6N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUU9NG6N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUU9NG6N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUU9NG6N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUU9NG6N\App_KernelDevDebugContainer([
    'container.build_hash' => 'UU9NG6N',
    'container.build_id' => '29e75b7b',
    'container.build_time' => 1583619024,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUU9NG6N');
