<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIgs4Xx9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIgs4Xx9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIgs4Xx9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIgs4Xx9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIgs4Xx9\App_KernelDevDebugContainer([
    'container.build_hash' => 'Igs4Xx9',
    'container.build_id' => '65d16735',
    'container.build_time' => 1579856583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIgs4Xx9');
